# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab57e8e3cd06ed2e3e5dfbc5ebba43f326f932174efdc9c9b9f82f771db032af46065d1dba4ada21c50573b39a64872e6dfe59ae0456f7120ba19ba771973b6

test:
  secret_key_base: a99fb20ed7fcb31f37dde17fa76a00c000f0064a787ac5709f5e6f7102ba30115c9784eb19b97658bfc0c9462bce4ad5b03eb60368aa454b11538e6b3ab62fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
